### ISSUE TITLE
Error saving the results from L5

### ISSUE THREAD

**Issue by gejola** [OzFlux/PyFluxPro#54]
Hi,
 It seems there is a problem with the latest version of HDF5. At least I encountered this error when I try to save the results of the L5 step:

  INFO Opening netCDF file Umiujaq_2018_L5.nc
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 139798633355072:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
12:12:34 ERROR  Unable to open netCDF file /home/lackner/PyFluxPro/Master/output/UM_18/Umiujaq_2018_L5.nc for writing
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/lackner/anaconda2/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "PyFluxPro.py", line 617, in do_l5qc
    pfp_io.nc_write_series(ncFile, ds5, outputlist=outputlist)         # save the L5 data
  File "scripts/pfp_io.py", line 1897, in nc_write_series
    nc_write_globalattributes(ncFile, ds)
  File "scripts/pfp_io.py", line 1872, in nc_write_globalattributes
    setattr(nc_file,item,attr)
AttributeError: 'str' object has no attribute 'BulkDensity'

Thanks for the help,
Georg Lackner

**Comment by pisaac-ozflux** [comment]
Hi Georg,

As per email, deleting the existing L5 netCDF file will fix this problem.  Sometimes, the OS leaves the netCDF file locked for whatever reason and so subsequent overwrites fail.

Cheers,
Peter
