### ISSUE TITLE
BUG: u* threshold MPT executable not found

### ISSUE THREAD

**Issue by danmet** [OzFlux/PyFluxPro#69]
Hi Peter,
ustar_mp.exe seems to end up in the wrong folder when cloning PyFluxPro on linux (Solus 4.0). 

![mpt_linux_bug](https://user-images.githubusercontent.com/33299176/60307944-07635e00-998a-11e9-8b44-f093df88084a.png)

**Comment by pisaac-ozflux** [comment]
Hi Dan,

I have added a shell script file (make_nix) to the PyFluxPro directory to build the required executables and move them to the appropriate bin directories plus added text to describe the process to the repository readme.md file.

If this is enough for now (pending a better install process), can we mark this as closed?

Cheers,
Peter
